### ISSUE TITLE
Skyler Smith

### ISSUE THREAD

**Issue by smith897** [BYUCS452F2021/moneywatcher#1]
Hi there!

My name is Skyler Smith. I've also been a little disappointed with budgeting apps in the past and would love the chance to work on an app that improves on the process.

I've built full stack applications for several development teams, some of which include the BYU Silver Fund Web App for the school of business, a ROS based system for robot manipulation, and a web based interactive game in Dr. Crandall's research lab. I'm also currently enrolled in the Software Engineering capstone, where we are also building full stack applications for companies in small teams, while learning about efficient practices for development teams.

As far as front end technologies, I've taken Google's course on modern android development in Kotlin, and I have experience in Java as well. I've built web apps in Vue, and in React. I also am experienced in Flutter, Google's development kit which allows an app to be released on Android, iOS, Web, and Desktop from one codebase. For back end technologies, I've worked on projects using Node.js and MongoDB, I've built several apps using AWS, the Serverless framework, and Firebase. I generally learn new technologies quickly, and am of course open to learning something new as well.

Thank you for considering me! Let me know if you think I would be a good fit!

**Comment by Cully333** [comment]
I'd like to be part of the team for this project. I love the idea of a simple, lightweight budgeting application, and I think that others could find it useful as well. I have some experience with web and android applications, but I would be willing to learn whatever is needed to contribute. Let me know what you think.

**Comment by smith897** [comment]
@h2coder88 Do you know when you'll be choosing your group members?

**Comment by h2coder88** [comment]
@smith897 Thanks for reaching out! I would love you have you and @Cully333 on the team.  I am excited to get to know you both and think you both have great skills to offer the team.  Thank you for your interest.
