### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by Cully333** [BYUCS452F2021/moneywatcher#2]
I'd like to be part of the team for this project. I love the idea of a simple, lightweight budgeting application, and I think that others could find it useful as well. I have some experience with web and android applications, but I would be willing to learn whatever is needed to contribute. Let me know what you think.

**Comment by h2coder88** [comment]
I'd love to have your help on the project! Thank you for your interest.

**Comment by h2coder88** [comment]
@Cully333 Could you post your name here or DM me on the class slack channel?

**Comment by Cully333** [comment]
Whoops, forgot to type it originally. My name is Cullen Steig.
